name: Deploy Bicep using ARM Deploy

on:
  workflow_dispatch:
    inputs:
      azureRgName:
        description: 'Azure Resource Group Name'
        required: true
        default: 'rg-bicep-osa-002'
      environmentType:
        description: 'Environment type (nonprod or prod)'
        required: true
        default: 'nonprod'
      deployAmeretatManualsStorageAccount:
        description: 'Deploy Ameretat Manuals Storage Account (true or false)'
        required: true
        default: 'true'

# OIDC認証を使用してAzureにログインしている場合（id-token: write が必要）
# リポジトリからBicepファイルを取得している場合（contents: read が必要）
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Azure CLIでのログイン
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # 必要に応じてリポジトリをチェックアウト
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    # 定義したパラメータを確認
    - name: 'Set parameters as environment variables'
      run: |
        echo "ENVIRONMENT_TYPE=${{ github.event.inputs.environmentType }}"
        echo "DEPLOY_AMERETAT_STORAGE=${{ github.event.inputs.deployAmeretatManualsStorageAccount }}"

    # ARM Deployを使用したBicepファイルのデプロイ
    - name: 'Deploy Bicep file'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ github.event.inputs.azureRgName }}
        template: deploy/main.bicep
        parameters: >
          environmentType=${{ github.event.inputs.environmentType }}
          deployAmeretatManualsStorageAccount=${{ github.event.inputs.deployAmeretatManualsStorageAccount }}
        deploymentMode: Incremental
        failOnStdErr: false
